# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_featuresrht_wrapper <- function(X, y, X_test_in, y_test_in, r, bins, alpha, run_uni, run_top, run_lev, run_sup) {
    .Call(`_class_run_featuresrht_wrapper`, X, y, X_test_in, y_test_in, r, bins, alpha, run_uni, run_top, run_lev, run_sup)
}

IBOSS_cpp <- function(X, y, k, intercept = FALSE) {
    .Call(`_class_IBOSS_cpp`, X, y, k, intercept)
}

kBOSS <- function(X, y, freqs, k_iboss) {
    .Call(`_class_kBOSS`, X, y, freqs, k_iboss)
}

SRHT_cpp <- function(X, y, r) {
    .Call(`_class_SRHT_cpp`, X, y, r)
}

fast_subsample <- function(X, y, nSample) {
    .Call(`_class_fast_subsample`, X, y, nSample)
}

r2 <- function(y_true, y_pred) {
    .Call(`_class_r2`, y_true, y_pred)
}

MSE <- function(y_true, y_pred) {
    .Call(`_class_MSE`, y_true, y_pred)
}

betaOLS_closed <- function(X, y) {
    .Call(`_class_betaOLS_closed`, X, y)
}

